version: '2'
volumes:
  db:
  node_modules:
  deps:
  build:

services:
  db:
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: active_monitoring_dev
    volumes:
      - 'db:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  app:
    command: elixir --sname server -S mix phoenix.server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    working_dir: /app
    depends_on:
      - db
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      GUISSO_CLIENT_ID: ${GUISSO_CLIENT_ID}
      GUISSO_CLIENT_SECRET: ${GUISSO_CLIENT_SECRET}
      GUISSO_REDIRECT_URI: ${GUISSO_REDIRECT_URI}
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
    ports:
      - 4000:80

  webpack:
    build:
      context: ./
      dockerfile: Dockerfile.webpack
    command: yarn watch
    stdin_open: true
    tty: true
    restart: always
    working_dir: /app
    stop_signal: SIGKILL
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'node_modules:/app/node_modules'

  ngrok:
    image: wernight/ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PORT: 'app:80'
